import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { useTicket } from '@org/core';
import { useParams } from 'react-router';
import { Sparkles } from 'lucide-react';

const TicketTagsCard = () => {
  const { orgId, ticketId } = useParams();
  const { ticketDetails, isLoadingTicketDetails } = useTicket({
    orgId,
    ticketId,
  });

  const tags = ticketDetails?.data.keywords ?? [];
  const sentiment = ticketDetails?.data.sentiment;
  const language = ticketDetails?.data.language;

  const sentimentVariant =
    sentiment?.toLowerCase() === 'positive'
      ? 'default'
      : sentiment?.toLowerCase() === 'negative'
        ? 'destructive'
        : 'secondary';

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0">
        <div>
          <CardTitle className="flex items-center gap-2">
            Tags
            <span
              className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary"
              title="Generated by AI"
            >
              <Sparkles className="h-3 w-3" />
              AI
            </span>
          </CardTitle>
          <CardDescription>Labels, sentiment &amp; keywords</CardDescription>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Tags */}
        <div>
          <p className="mb-2 text-xs font-medium text-muted-foreground">Tags</p>
          <div className="flex flex-wrap gap-2">
            {isLoadingTicketDetails ? (
              <>
                <Skeleton className="h-6 w-16" />
                <Skeleton className="h-6 w-12" />
                <Skeleton className="h-6 w-20" />
              </>
            ) : tags.length > 0 ? (
              tags.map((tag) => (
                <Badge key={tag} variant="outline" className="capitalize">
                  {tag}
                </Badge>
              ))
            ) : (
              <span className="text-sm text-muted-foreground italic">
                No tags yet.
              </span>
            )}
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          {/* Sentiment */}
          <div>
            <p className="mb-1 text-xs font-medium text-muted-foreground">
              Sentiment
            </p>
            {isLoadingTicketDetails ? (
              <Skeleton className="h-6 w-20" />
            ) : sentiment ? (
              <Badge variant={sentimentVariant} className="capitalize">
                {sentiment}
              </Badge>
            ) : (
              <span className="text-sm text-muted-foreground italic">N/A</span>
            )}
          </div>

          {/* Language */}
          <div>
            <p className="mb-1 text-xs font-medium text-muted-foreground">
              Language
            </p>
            {isLoadingTicketDetails ? (
              <Skeleton className="h-6 w-16" />
            ) : language ? (
              <Badge variant="secondary" className="uppercase">
                {language}
              </Badge>
            ) : (
              <span className="text-sm text-muted-foreground italic">N/A</span>
            )}
          </div>
        </div>
        <div>
          {/* Keywords */}
          <p className="mb-1 text-xs font-medium text-muted-foreground">
            AI confidence
          </p>
          {isLoadingTicketDetails ? (
            <Skeleton className="h-6 w-32" />
          ) : (
            ticketDetails?.data.confidence && (
              <Badge variant="outline">
                {ticketDetails?.data.confidence * 100} %
              </Badge>
            )
          )}
        </div>
      </CardContent>
    </Card>
  );
};

export default TicketTagsCard;
