services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - prisma-network

  backend:
    build:
      context: .
      target: backend
    image: rajwindersxxx/ticket-management:backend
    env_file:
      - .env
    environment:
      - PORT=3000
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - BETTER_AUTH_URL=http://localhost

    healthcheck:
      test: [
        "CMD-SHELL",
        'node -e "require(\"http\").get(\"http://localhost:3000\", (r) => process.exit(r.statusCode === 200 ? 0 : 1))"'
      ]
      retries: 5
    depends_on:
      - redis  
    networks:
      - prisma-network

  email-service: # Note: watch out for the typo in "workder" if you want to fix it later!
    build:
      context: .
      target: email-service
    image: rajwindersxxx/ticket-management:email-service
    env_file:
      - .env
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - prisma-network # ADDED: Essential so it can see the redis container

  frontend:
    build:
      context: .
      target: frontend
    image: rajwindersxxx/ticket-management:frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - prisma-network

networks:
  prisma-network:

volumes:
  redis-data:
