name = "ticketflow-proxy"
main = "worker.js"
compatibility_date = "2026-07-15"

routes = [
  { pattern = "ticketflow.devtiven.com/api/*", zone_name = "devtiven.com" },
  { pattern = "ticketflow.devtiven.com/webhooks/*", zone_name = "devtiven.com" },
]
